services:
  - type: web-service
    name: gavinlegay
    runtime: docker
    repo : git@github.com:vithushan77/deployement.git
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter instance type)
    branch: main # optional (defaults to master)
    rootDir: gavinlegay

databases:
  - name: elephant
    databaseName: mydb # optional (Render may add a suffix)
    user: adrian # optional
