services:
  - name: cloud-web
    type: web
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/ArchOrn/render-deploy-blueprint.git
    branch: main
    region: frankfurt
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-db
          property: connectionString

databases:
  - name: cloud-db
    databaseName: cloud
    user: cloud
    region: frankfurt
    plan: free